"use client"
import { useRouter } from 'next/navigation'
import { Inter } from 'next/font/google'
import './globals.css'
import Headar from '../component/Headar'
import { Suspense, useEffect, useState } from 'react'
import Loading from './movie/loading'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // const [Load, setLoading] = useState(false);
  // const router = useRouter()

  // const [count, setCount] = useState(0);
  // useEffect(() => {
  //   setCount(x => x + 1);
  //   console.log('route change with dependency', router.pathname,count);
  // }, [router.pathname]);

  // useEffect(() => {
  //   const handlestart = () => {
  //     setLoading(true)
  //   }
  //   const handlecomplete = () => {
  //     setLoading(false)
  //   }
  //   router.events.on("routeChangeStart", handlestart)


  //   router.events.on("routeChangeComplete", handlecomplete)


  //   router.events.on("routeChangeError", handlecomplete)


  //   return () => {
  //     router.events.off("routeChangeStart", handlestart)

  //     router.events.off("routeChangeComplete", handlecomplete)

  //     router.events.off("routeChangeError", handlecomplete)
  //   }

  // }, [router.events])

  return (
    <>

      {/* {Load ? <Loading /> : null} */}
      <Headar />
      {children}
    </>
  )
}
